//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HXWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserSex { get; set; }
        public string UserPhone { get; set; }
        public string UserAddress { get; set; }
        public Nullable<int> AddressID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Hospital { get; set; }
    }
}
